= Love4TheSystems

== Handling Version Update

Every month we are updating all existing

- plugins
- 3rd party dependencies

to the newest version.

== Version Management

For the version management we use the gradle link:https://docs.gradle.org/current/userguide/platforms.html[version catalog]
using a toml file.

The automatic version update is done by the link:https://github.com/littlerobots/version-catalog-update-plugin[version catalog update plugin]

== Version Configuration

All version used by **TechTrekker** project are defined in link:../gradle/libs.versions.toml[libs.versions.toml].
There are different sections available

=== [versions]

Defines all used versions (for plugins and dependencies).

=== [libraries]

Defines the 3rd party dependencies.

=== [bundles]

Defines the bundles (grouping of multiple libraries together).

=== [plugins]

Defines all used plugins.

There are 2 different annotations available to not update versions.

- **@pin**
The versions annotated with @pin are not automatically updated but kept in current version.

- **@keep**
The versions annotated with @keep are not removed because not used in dependencies/plugins at the moment.
This can be used e.g. for jdk version.

== How version update is done

There are the following steps necessary for updating:
- Run  `./gradlew versionCatalogUpdate --interactive`.
This creates libs.versions.updates.toml file with content similar to

